#!/usr/bin/env python
# Standard godot-cpp SConstruct. Requires godot-cpp checked out at ./godot-cpp.
import os

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

lib_name = "intelforge"
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "bin/lib{}.{}.{}.framework/lib{}.{}.{}".format(
            lib_name, env["platform"], env["target"], lib_name, env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/lib{}{}{}".format(lib_name, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
