#!/usr/bin/env python3
"""Generate Ink dialogue for the standing cast from topics.json.

`topics.json` decides what is POSSIBLE; this generates what it SOUNDS LIKE
for every NPC not on the hand-written list (see CONVERSATION_GENERATOR.md).
Never touches a hand-written file, and never overwrites a file that lacks its
own generated header -- that is the safety rail that lets a human claim a
character permanently just by deleting one line.

Voice model: `ink/corvin.ink`, the proven hand-written pattern. Generated
prose is plainer than Corvin's but follows the same shape: the mill hedges,
a real source explains once, a bought answer costs a bribe, a stonewalled
answer needs proof. Every line is tagged for a later human pass.

    python gen_dialogue.py            # write games/slack_tide/ink/<npc>.ink
    python gen_dialogue.py --check    # exit 1 if any generated file is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

GAME = Path(__file__).resolve().parents[1]
SPEC = GAME / "docs" / "slack_tide_spec.json"
TOPICS = GAME / "topics.json"
INK_DIR = GAME / "ink"

HEADER_MARK = "// *** GENERATED by tools/gen_dialogue.py"

# The five who carry the story get hand-written files and are never touched.
BESPOKE = {"corvin", "doon", "brack", "hesper", "wenna"}

# A voice fragment per standing NPC: one hedge, one tic, one refusal line, so
# generated prose does not read as interchangeable. Drawn from each NPC's
# `role` line in the spec, kept short on purpose -- these are seasoning, not
# a substitute for the bespoke five carrying the emotional load.
VOICE = {
    "doss": {"hedge": "shrugs, not unkindly", "tic": "counts coin while he talks",
              "refuse": "\"Ask someone who's paid to know.\""},
    "cobb": {"hedge": "wipes a glass that was already clean",
              "tic": "says \"mind\" a lot, meaning several things by it",
              "refuse": "\"Not while you're owing me for Tuesday.\""},
    "fen": {"hedge": "looks at the water before he answers",
             "tic": "measures everything against a tide he remembers",
             "refuse": "\"Come back when the ebb's not running my mouth.\""},
    "ottoline": {"hedge": "closes the ledger a half-inch, meaningfully",
                  "tic": "quotes a price before you have asked a question",
                  "refuse": "\"Coin first. This isn't a chapel.\""},
    "wimble": {"hedge": "glances at the door to Vosk's old office",
                "tic": "stamps things that do not need stamping",
                "refuse": "\"That's a fee, not a favour.\""},
    "vosk": {"hedge": "folds her hands the way she once folded a warrant",
              "tic": "still calls the customs house \"my desk\"",
              "refuse": "\"I retired from doing things for free.\""},
    "croy": {"hedge": "trims a wick he does not need to trim",
              "tic": "talks to the lamp before he talks to you",
              "refuse": "\"The light's not for sale. Ask it something else.\""},
    "yarrow": {"hedge": "holds a thing up to the light before answering",
                "tic": "finishes your sentence wrong on purpose",
                "refuse": "\"That one costs more than you've got.\""},
    "toma": {"hedge": "keeps working the net while he talks",
              "tic": "measures trust in eels, not tallies",
              "refuse": "\"Not for coin. Bring something that swims.\""},
    "goldie": {"hedge": "totals your bill before you've picked anything up",
                "tic": "narrates the shelf like a shopkeeper's prayer",
                "refuse": "\"Pay the tab first, then we'll talk.\""},
}

MODE_NAMES = {"explain": "explain", "rumor": "rumor", "price": "price",
              "flinch": "flinch"}


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def is_bespoke_file(path: Path) -> bool:
    """A file the generator must never touch: hand-written, or missing the
    generated header (which is the contract that lets a human claim it)."""
    if not path.exists():
        return False
    head = path.read_text(encoding="utf-8")[:400]
    return HEADER_MARK not in head


def topic_stances(topics: dict, npc: str) -> list[tuple[str, dict]]:
    out = []
    for tid, t in topics.get("topics", {}).items():
        st = t.get("stances", {}).get(npc)
        if st:
            out.append((tid, {**t, "stance": st}))
    return out


def token_name(spec_tokens: dict, tid: str) -> str:
    t = spec_tokens.get(tid)
    return t["name"] if t else tid


def knot_name(topic_id: str) -> str:
    return "topic_" + topic_id.replace("-", "_")


def build_npc_ink(npc_id: str, npc: dict, topics: dict, spec_tokens: dict) -> str:
    voice = VOICE.get(npc_id, {"hedge": "considers the question",
                                "tic": "answers plainly",
                                "refuse": "\"Not today.\""})
    stances = topic_stances(topics, npc_id)
    name = npc.get("name", npc_id.title())
    role = npc.get("role", "")

    lines: list[str] = []
    lines.append(f"// ============================================================")
    lines.append(f"// {name} -- {role}")
    lines.append(f"// ============================================================")
    lines.append(HEADER_MARK + " from topics.json. Edit docs/slack_tide_spec.json")
    lines.append("// and topics.json, not this file; re-run to regenerate.")
    lines.append("// Every line below is a functional draft: # NEEDS_HUMAN_WRITING")
    lines.append("// ============================================================")
    lines.append("")
    lines.append("INCLUDE patterns.ink")
    lines.append("")
    lines.append(f'VAR npc_id = "{npc_id}"')
    lines.append(f'VAR location = "{npc.get("location", "")}"')
    lines.append('VAR npc_standing = "neutral"')
    lines.append("")
    lines.append("")
    lines.append(f"=== {npc_id} ===")
    lines.append(f"{name} {voice['tic']}.  # NEEDS_HUMAN_WRITING")
    lines.append("- (hub)")
    lines.append(f'+ ["How are you keeping?"] -> {npc_id}_smalltalk')
    for tid, t in stances:
        label = t.get("name", tid)
        lines.append(f'+ [Ask about {label.lower()}.] -> {knot_name(tid)}')
    lines.append("+ [Leave them to it.] -> END")
    lines.append("")
    lines.append("")
    lines.append(f"= {npc_id}_smalltalk")
    lines.append(f"They {voice['hedge']}.  # NEEDS_HUMAN_WRITING")
    lines.append("-> hub")
    lines.append("")

    for tid, t in stances:
        lines.extend(build_topic_knot(npc_id, tid, t, voice, spec_tokens))

    return "\n".join(lines) + "\n"


def build_topic_knot(npc_id: str, topic_id: str, topic: dict, voice: dict,
                     spec_tokens: dict) -> list[str]:
    st = topic["stance"]
    mode = st.get("mode", "explain")
    kname = knot_name(topic_id)
    out = ["", ""]
    out.append(f"= {kname}")

    if mode == "explain":
        method = st.get("method", "told")
        grants = st.get("grants", [])
        out.append(f"They {voice['tic']}, and this time it means something.  "
                   f"# NEEDS_HUMAN_WRITING")
        for tid in grants:
            tname = token_name(spec_tokens, tid)
            out.append(f'"{tname}." They say it once and do not repeat it.  '
                       f'# NEEDS_HUMAN_WRITING')
            out.append(f'~ learn("{tid}", 1.0)')
        out.append("-> hub")

    elif mode == "rumor":
        grants = st.get("grants", [])
        cap = float(st.get("cap", 25)) / 100.0
        out.append(f"They {voice['hedge']}. \"Depends who you ask.\"  "
                   f"# NEEDS_HUMAN_WRITING")
        for tid in grants:
            tname = token_name(spec_tokens, tid)
            out.append(f'+ ["Is it true that {tname.lower()}?"]')
            out.append(f'    "Could be. I heard {tname.lower()}, for what '
                       f'that\'s worth."  # NEEDS_HUMAN_WRITING')
            out.append(f'    ~ learn("{tid}", {cap:.2f})')
            out.append(f'    -> {kname}')
        out.append("+ [Leave it there.] -> hub")

    elif mode == "price":
        buys = st.get("buys", st.get("grants", []))
        price = int(st.get("price", 8))
        currency = "tally"
        for tid in buys:
            tname = token_name(spec_tokens, tid)
            out.append(f'+ {{ has_asset("tally", {price}) }} [Pay for word of '
                       f'{tname.lower()}. ({price} tallies)]')
            out.append(f'    -> barter("{tid}", 1, "{currency}", {price}, '
                       f'npc_id, "") ->')
            out.append('    { barter_result == BARTER_BOUGHT:')
            out.append(f'        ~ learn("{tid}", 0.60)')
            out.append(f'        "{tname}." They {voice["tic"]}.  '
                       f'# NEEDS_HUMAN_WRITING')
            out.append("    }")
            out.append("    -> hub")
            out.append(f'+ [Ask the price of {tname.lower()}, empty-handed.]')
            out.append(f'    "{price} tallies. Coin first."  '
                       f'# NEEDS_HUMAN_WRITING')
            out.append("    -> hub")
        out.append("+ [Not today.] -> hub")

    elif mode == "flinch":
        grants = st.get("grants", [])
        for tid in grants:
            tname = token_name(spec_tokens, tid)
            out.append(f'+ {{ knows("{tid}") }} [Press them on it -- you '
                       f'already know.]')
            out.append(f'    They {voice["hedge"]}, and then they slip.  '
                       f'# NEEDS_HUMAN_WRITING')
            out.append(f'    ~ learn("{tid}", 1.0)')
            out.append("    -> hub")
        out.append(f'+ [Ask anyway.] {voice["refuse"]}  # NEEDS_HUMAN_WRITING')
        out.append("    -> hub")

    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    spec = load(SPEC)
    topics = load(TOPICS)
    spec_tokens = {t["id"]: t for t in spec["tokens"]}
    npcs = spec.get("npcs", {})

    # Standing cast = anyone in npcs{} who speaks in topics.json and is not
    # one of the five bespoke, story-carrying characters.
    speakers: set[str] = set()
    for t in topics.get("topics", {}).values():
        speakers.update(t.get("stances", {}))
    to_generate = sorted(n for n in speakers
                         if n in npcs and n not in BESPOKE)

    stale: list[str] = []
    written: list[str] = []
    skipped_bespoke: list[str] = []

    for npc_id in to_generate:
        path = INK_DIR / f"{npc_id}.ink"
        if is_bespoke_file(path):
            skipped_bespoke.append(npc_id)
            continue
        text = build_npc_ink(npc_id, npcs[npc_id], topics, spec_tokens)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(npc_id)
            continue
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            written.append(npc_id)

    if args.check:
        if stale:
            print(f"{len(stale)} generated .ink file(s) stale: "
                  f"{', '.join(stale)}", file=sys.stderr)
            print("Run: python games/slack_tide/tools/gen_dialogue.py",
                  file=sys.stderr)
            return 1
        print(f"dialogue up to date ({len(to_generate)} generated NPCs, "
              f"{len(BESPOKE)} bespoke)")
        return 0

    print(f"gen_dialogue: {len(written)} written/updated, "
          f"{len(to_generate) - len(written) - len(skipped_bespoke)} unchanged, "
          f"{len(skipped_bespoke)} skipped (claimed by hand-writing: "
          f"{', '.join(skipped_bespoke) if skipped_bespoke else 'none'})")
    print(f"bespoke (never generated): {', '.join(sorted(BESPOKE))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
