// ============================================================
// Ma Cobb -- Landlady of the Low Lantern. Hears everything.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "cobb"
VAR location = "low_lantern"
VAR npc_standing = "neutral"


=== cobb ===
Ma Cobb says "mind" a lot, meaning several things by it.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> cobb_smalltalk
+ [Ask about what lives down there.] -> topic_beast
+ [Ask about who is paying whom.] -> topic_econ
+ [Ask about people.] -> topic_people
+ [Ask about where it is safe to walk.] -> topic_place
+ [Ask about route.] -> topic_route
+ [Ask about what people would rather keep.] -> topic_secret
+ [Ask about the weirkeeper works the sluice.] -> topic_q1
+ [Ask about harrow was silenced.] -> topic_q2
+ [Ask about the satchel holds doon's plea.] -> topic_q3
+ [Ask about it begins at the gatehouse.] -> topic_q4
+ [Ask about only the assize can free doon.] -> topic_q5
+ [Leave them to it.] -> END


= cobb_smalltalk
They wipes a glass that was already clean.  # NEEDS_HUMAN_WRITING
-> hub



= topic_beast
They says "mind" a lot, meaning several things by it, and this time it means something.  # NEEDS_HUMAN_WRITING
"The kelpmother takes eels." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_kelp_tribute", 1.0)
"Pay the Collector." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_collector_toll", 1.0)
-> hub


= topic_econ
They says "mind" a lot, meaning several things by it, and this time it means something.  # NEEDS_HUMAN_WRITING
"A sold secret loses value." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_spread_drops", 1.0)
"Smugglers tip to be ignored." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_smuggler_tip", 1.0)
"Fares double after the first week." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_fare_hike", 1.0)
-> hub


= topic_people
They says "mind" a lot, meaning several things by it, and this time it means something.  # NEEDS_HUMAN_WRITING
"Hesper prizes a kept word." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_hesper", 1.0)
"Discount Doss by half." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_doss", 1.0)
"Fen is good before noon." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_fen", 1.0)
"Toma deals fair or not at all." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_toma", 1.0)
"Doon answers to her oath." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_doon", 1.0)
"Corvin's pouch bears the Tally seal." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_corvin", 1.0)
-> hub


= topic_place
They says "mind" a lot, meaning several things by it, and this time it means something.  # NEEDS_HUMAN_WRITING
"Each slack runs longer." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_slack_grows", 1.0)
"Follow the heron-stones." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_heron_stones", 1.0)
-> hub


= topic_route
They says "mind" a lot, meaning several things by it, and this time it means something.  # NEEDS_HUMAN_WRITING
"Turning Word: second." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("r_word_2", 1.0)
-> hub


= topic_secret
They says "mind" a lot, meaning several things by it, and this time it means something.  # NEEDS_HUMAN_WRITING
"Doss skims the fares." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("s_doss_skims", 1.0)
"Corvin's brother drowned." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("s_corvin_brother", 1.0)
-> hub


= topic_q1
They wipes a glass that was already clean. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that the weirkeeper works the sluice?"]
    "Could be. I heard the weirkeeper works the sluice, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c1a", 0.25)
    -> topic_q1
+ ["Is it true that hirelings work the sluice?"]
    "Could be. I heard hirelings work the sluice, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c1b", 0.25)
    -> topic_q1
+ ["Is it true that nobody works the sluice?"]
    "Could be. I heard nobody works the sluice, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c1c", 0.25)
    -> topic_q1
+ [Leave it there.] -> hub


= topic_q2
They wipes a glass that was already clean. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that harrow was silenced?"]
    "Could be. I heard harrow was silenced, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c2a", 0.25)
    -> topic_q2
+ ["Is it true that harrow was chased?"]
    "Could be. I heard harrow was chased, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c2b", 0.25)
    -> topic_q2
+ ["Is it true that harrow was taken by the stairs?"]
    "Could be. I heard harrow was taken by the stairs, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c2c", 0.25)
    -> topic_q2
+ [Leave it there.] -> hub


= topic_q3
They wipes a glass that was already clean. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that the satchel holds doon's plea?"]
    "Could be. I heard the satchel holds doon's plea, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c3a", 0.25)
    -> topic_q3
+ ["Is it true that the satchel holds the log?"]
    "Could be. I heard the satchel holds the log, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c3b", 0.25)
    -> topic_q3
+ ["Is it true that the satchel holds a hum chart?"]
    "Could be. I heard the satchel holds a hum chart, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c3c", 0.25)
    -> topic_q3
+ [Leave it there.] -> hub


= topic_q4
They wipes a glass that was already clean. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that it begins at the gatehouse?"]
    "Could be. I heard it begins at the gatehouse, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c4a", 0.25)
    -> topic_q4
+ ["Is it true that it begins at the marl sluice-house?"]
    "Could be. I heard it begins at the marl sluice-house, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c4b", 0.25)
    -> topic_q4
+ ["Is it true that it begins beneath the steps?"]
    "Could be. I heard it begins beneath the steps, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c4c", 0.25)
    -> topic_q4
+ [Leave it there.] -> hub


= topic_q5
They wipes a glass that was already clean. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that only the assize can free doon?"]
    "Could be. I heard only the assize can free doon, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c5a", 0.25)
    -> topic_q5
+ ["Is it true that expose the ledger?"]
    "Could be. I heard expose the ledger, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c5b", 0.25)
    -> topic_q5
+ ["Is it true that ring the bell?"]
    "Could be. I heard ring the bell, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c5c", 0.25)
    -> topic_q5
+ [Leave it there.] -> hub
