// ============================================================
// The Pale Collector -- Toll-ghost of the Salt Steps.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "collector"
VAR location = "salt_steps"
VAR npc_standing = "neutral"


=== collector ===
The Pale Collector answers plainly.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> collector_smalltalk
+ [Ask about where it is safe to walk.] -> topic_place
+ [Leave them to it.] -> END


= collector_smalltalk
They considers the question.  # NEEDS_HUMAN_WRITING
-> hub



= topic_place
They answers plainly, and this time it means something.  # NEEDS_HUMAN_WRITING
"Drowned marks still spend." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_old_coin", 1.0)
-> hub
