// ============================================================
// Ansel Croy -- Old lampwright. Gift: Warding Wick.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "croy"
VAR location = "croy_lighthouse"
VAR npc_standing = "neutral"


=== croy ===
Ansel Croy talks to the lamp before he talks to you.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> croy_smalltalk
+ [Ask about what lives down there.] -> topic_beast
+ [Ask about people.] -> topic_people
+ [Ask about where it is safe to walk.] -> topic_place
+ [Ask about route.] -> topic_route
+ [Leave them to it.] -> END


= croy_smalltalk
They trims a wick he does not need to trim.  # NEEDS_HUMAN_WRITING
-> hub



= topic_beast
They talks to the lamp before he talks to you, and this time it means something.  # NEEDS_HUMAN_WRITING
"Salt stops a wight." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_wight_salt", 1.0)
"The Choir fears flame." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_choir_wick", 1.0)
-> hub


= topic_people
They talks to the lamp before he talks to you, and this time it means something.  # NEEDS_HUMAN_WRITING
"Croy keeps a wick-staff." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_croy", 1.0)
"Yarrow's glass catches lies." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_yarrow", 1.0)
"Brack's blade drank the Lull." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_brack", 1.0)
-> hub


= topic_place
They talks to the lamp before he talks to you, and this time it means something.  # NEEDS_HUMAN_WRITING
"Croy's lamp calls the ferry." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_lighthouse", 1.0)
-> hub


= topic_route
They talks to the lamp before he talks to you, and this time it means something.  # NEEDS_HUMAN_WRITING
"Turning Word: first." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("r_word_1", 1.0)
"Turning Word: second." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("r_word_2", 1.0)
-> hub
