// ============================================================
// Doss Pellam -- Fellow deckhand. Gossip, skimmer, rumor mill.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "doss"
VAR location = "ferry_deck"
VAR npc_standing = "neutral"


=== doss ===
Doss Pellam counts coin while he talks.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> doss_smalltalk
+ [Ask about who is paying whom.] -> topic_econ
+ [Ask about people.] -> topic_people
+ [Ask about what people would rather keep.] -> topic_secret
+ [Ask about doon's lantern log.] -> topic_ev_a
+ [Ask about tally chit for the sluice crew.] -> topic_ev_b
+ [Ask about the weirkeeper works the sluice.] -> topic_q1
+ [Ask about harrow was silenced.] -> topic_q2
+ [Ask about the satchel holds doon's plea.] -> topic_q3
+ [Ask about it begins at the gatehouse.] -> topic_q4
+ [Ask about only the assize can free doon.] -> topic_q5
+ [Leave them to it.] -> END


= doss_smalltalk
They shrugs, not unkindly.  # NEEDS_HUMAN_WRITING
-> hub



= topic_econ
They counts coin while he talks, and this time it means something.  # NEEDS_HUMAN_WRITING
"Smugglers tip to be ignored." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_smuggler_tip", 1.0)
"The cellar costs eight." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_customs_bribe", 1.0)
-> hub


= topic_people
They counts coin while he talks, and this time it means something.  # NEEDS_HUMAN_WRITING
"Discount Doss by half." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_doss", 1.0)
-> hub


= topic_secret
They counts coin while he talks, and this time it means something.  # NEEDS_HUMAN_WRITING
"Wimble sells the records." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("s_wimble_sells", 1.0)
"Smugglers use the Marl wharf." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("s_marl_smugglers", 1.0)
-> hub


= topic_ev_a
They counts coin while he talks, and this time it means something.  # NEEDS_HUMAN_WRITING
"A lantern log, too fresh." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("fg_a_lantern", 1.0)
-> hub


= topic_ev_b
They counts coin while he talks, and this time it means something.  # NEEDS_HUMAN_WRITING
"A Tally chit, seal off." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("fg_b_paystub", 1.0)
-> hub


= topic_q1
They shrugs, not unkindly. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that the weirkeeper works the sluice?"]
    "Could be. I heard the weirkeeper works the sluice, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c1a", 0.25)
    -> topic_q1
+ ["Is it true that hirelings work the sluice?"]
    "Could be. I heard hirelings work the sluice, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c1b", 0.25)
    -> topic_q1
+ ["Is it true that nobody works the sluice?"]
    "Could be. I heard nobody works the sluice, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c1c", 0.25)
    -> topic_q1
+ [Leave it there.] -> hub


= topic_q2
They shrugs, not unkindly. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that harrow was silenced?"]
    "Could be. I heard harrow was silenced, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c2a", 0.25)
    -> topic_q2
+ ["Is it true that harrow was chased?"]
    "Could be. I heard harrow was chased, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c2b", 0.25)
    -> topic_q2
+ ["Is it true that harrow was taken by the stairs?"]
    "Could be. I heard harrow was taken by the stairs, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c2c", 0.25)
    -> topic_q2
+ [Leave it there.] -> hub


= topic_q3
They shrugs, not unkindly. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that the satchel holds doon's plea?"]
    "Could be. I heard the satchel holds doon's plea, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c3a", 0.25)
    -> topic_q3
+ ["Is it true that the satchel holds the log?"]
    "Could be. I heard the satchel holds the log, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c3b", 0.25)
    -> topic_q3
+ ["Is it true that the satchel holds a hum chart?"]
    "Could be. I heard the satchel holds a hum chart, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c3c", 0.25)
    -> topic_q3
+ [Leave it there.] -> hub


= topic_q4
They shrugs, not unkindly. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that it begins at the gatehouse?"]
    "Could be. I heard it begins at the gatehouse, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c4a", 0.25)
    -> topic_q4
+ ["Is it true that it begins at the marl sluice-house?"]
    "Could be. I heard it begins at the marl sluice-house, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c4b", 0.25)
    -> topic_q4
+ ["Is it true that it begins beneath the steps?"]
    "Could be. I heard it begins beneath the steps, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c4c", 0.25)
    -> topic_q4
+ [Leave it there.] -> hub


= topic_q5
They shrugs, not unkindly. "Depends who you ask."  # NEEDS_HUMAN_WRITING
+ ["Is it true that only the assize can free doon?"]
    "Could be. I heard only the assize can free doon, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c5a", 0.25)
    -> topic_q5
+ ["Is it true that expose the ledger?"]
    "Could be. I heard expose the ledger, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c5b", 0.25)
    -> topic_q5
+ ["Is it true that ring the bell?"]
    "Could be. I heard ring the bell, for what that's worth."  # NEEDS_HUMAN_WRITING
    ~ learn("c5c", 0.25)
    -> topic_q5
+ [Leave it there.] -> hub
