// ============================================================
// Fennick 'Fen' Aldous -- Old salvager. Tides, boats, the Stairs.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "fen"
VAR location = "low_lantern"
VAR npc_standing = "neutral"


=== fen ===
Fennick 'Fen' Aldous measures everything against a tide he remembers.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> fen_smalltalk
+ [Ask about what lives down there.] -> topic_beast
+ [Ask about who is paying whom.] -> topic_econ
+ [Ask about people.] -> topic_people
+ [Ask about where it is safe to walk.] -> topic_place
+ [Ask about route.] -> topic_route
+ [Ask about what people would rather keep.] -> topic_secret
+ [Ask about the weirkeeper works the sluice.] -> topic_q1
+ [Ask about it begins at the gatehouse.] -> topic_q4
+ [Leave them to it.] -> END


= fen_smalltalk
They looks at the water before he answers.  # NEEDS_HUMAN_WRITING
-> hub



= topic_beast
They measures everything against a tide he remembers, and this time it means something.  # NEEDS_HUMAN_WRITING
"Wights rise at slack." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_wight_slack", 1.0)
"The lullhound hunts by sound." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_lull_sound", 1.0)
"Pay the Collector." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_collector_toll", 1.0)
-> hub


= topic_econ
They measures everything against a tide he remembers, and this time it means something.  # NEEDS_HUMAN_WRITING
"Brass sells at Marl." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_scrap_price", 1.0)
"Boat hire is thirty." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_boat_hire", 1.0)
-> hub


= topic_people
They measures everything against a tide he remembers, and this time it means something.  # NEEDS_HUMAN_WRITING
"Ma Cobb hears the Reach." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_cobb", 1.0)
"Wenna keeps a tide-bell." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_wenna", 1.0)
"Doon answers to her oath." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_doon", 1.0)
-> hub


= topic_place
They measures everything against a tide he remembers, and this time it means something.  # NEEDS_HUMAN_WRITING
"The Steps are dry at ebb." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_lowebb", 1.0)
"Each slack runs longer." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_slack_grows", 1.0)
"The third stair is rotten." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_third_stair", 1.0)
"Drowned marks still spend." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_old_coin", 1.0)
"Three gates, one small." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_weir_gates", 1.0)
"The cistern goes under the Weir." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_cistern_way", 1.0)
"Full Slack stops the ferry." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_full_slack", 1.0)
-> hub


= topic_route
They measures everything against a tide he remembers, and this time it means something.  # NEEDS_HUMAN_WRITING
"Turning Word: first." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("r_word_1", 1.0)
"Knock twice, pause, once." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("r_cistern_knock", 1.0)
-> hub


= topic_secret
They measures everything against a tide he remembers, and this time it means something.  # NEEDS_HUMAN_WRITING
"Corvin's brother drowned." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("s_corvin_brother", 1.0)
"Doon's husband died at the Weir." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("s_doon_husband", 1.0)
-> hub


= topic_q1
They measures everything against a tide he remembers, and this time it means something.  # NEEDS_HUMAN_WRITING
"The Weirkeeper works the sluice." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("c1a", 1.0)
"Hirelings work the sluice." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("c1b", 1.0)
"Nobody works the sluice." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("c1c", 1.0)
-> hub


= topic_q4
They measures everything against a tide he remembers, and this time it means something.  # NEEDS_HUMAN_WRITING
"It begins at the gatehouse." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("c4a", 1.0)
-> hub
