// ============================================================
// Gatehouse guard -- Doon's oath-guards (A) or Tally hirelings (B). None in C.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "gatehouse_guard"
VAR location = "weir_gatehouse"
VAR npc_standing = "neutral"


=== gatehouse_guard ===
Gatehouse guard answers plainly.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> gatehouse_guard_smalltalk
+ [Ask about harrow was silenced.] -> topic_q2
+ [Ask about it begins at the gatehouse.] -> topic_q4
+ [Leave them to it.] -> END


= gatehouse_guard_smalltalk
They considers the question.  # NEEDS_HUMAN_WRITING
-> hub



= topic_q2
They answers plainly, and this time it means something.  # NEEDS_HUMAN_WRITING
"Harrow was silenced." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("c2a", 1.0)
-> hub


= topic_q4
They answers plainly, and this time it means something.  # NEEDS_HUMAN_WRITING
"It begins at the gatehouse." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("c4a", 1.0)
-> hub
