// ============================================================
// Marigold 'Goldie' Fenn -- Chandler at Ballast & Rope. Sells gear.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "goldie"
VAR location = "sorrel_landing"
VAR npc_standing = "neutral"


=== goldie ===
Marigold 'Goldie' Fenn narrates the shelf like a shopkeeper's prayer.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> goldie_smalltalk
+ [Ask about what lives down there.] -> topic_beast
+ [Ask about who is paying whom.] -> topic_econ
+ [Ask about people.] -> topic_people
+ [Leave them to it.] -> END


= goldie_smalltalk
They totals your bill before you've picked anything up.  # NEEDS_HUMAN_WRITING
-> hub



= topic_beast
They narrates the shelf like a shopkeeper's prayer, and this time it means something.  # NEEDS_HUMAN_WRITING
"Salt stops a wight." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_wight_salt", 1.0)
"Gulchers shy from iron." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_gulcher_iron", 1.0)
"A clatter draws it off." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_lull_decoy", 1.0)
-> hub


= topic_econ
They narrates the shelf like a shopkeeper's prayer, and this time it means something.  # NEEDS_HUMAN_WRITING
"Goldie rewards fair dealers." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_goldie_discount", 1.0)
"Brass sells at Marl." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_scrap_price", 1.0)
"Eels cost six a bundle." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_eel_market", 1.0)
-> hub


= topic_people
They narrates the shelf like a shopkeeper's prayer, and this time it means something.  # NEEDS_HUMAN_WRITING
"Toma deals fair or not at all." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_toma", 1.0)
-> hub
