// ============================================================
// Ottoline Prewitt -- Head clerk and info broker, Tally & Prewitt.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "ottoline"
VAR location = "tally_house"
VAR npc_standing = "neutral"


=== ottoline ===
Ottoline Prewitt quotes a price before you have asked a question.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> ottoline_smalltalk
+ [Ask about who is paying whom.] -> topic_econ
+ [Ask about people.] -> topic_people
+ [Ask about what people would rather keep.] -> topic_secret
+ [Ask about it begins at the gatehouse.] -> topic_q4
+ [Ask about only the assize can free doon.] -> topic_q5
+ [Leave them to it.] -> END


= ottoline_smalltalk
They closes the ledger a half-inch, meaningfully.  # NEEDS_HUMAN_WRITING
-> hub



= topic_econ
+ { has_asset("tally", 8) } [Pay for word of hearsay sells at half. (8 tallies)]
    -> barter("e_hearsay_half", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("e_hearsay_half", 0.60)
        "Hearsay sells at half." They quotes a price before you have asked a question.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of hearsay sells at half, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ { has_asset("tally", 8) } [Pay for word of a sold secret loses value. (8 tallies)]
    -> barter("e_spread_drops", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("e_spread_drops", 0.60)
        "A sold secret loses value." They quotes a price before you have asked a question.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of a sold secret loses value, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_people
+ { has_asset("tally", 8) } [Pay for word of vosk never broke a seal. (8 tallies)]
    -> barter("p_vosk", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("p_vosk", 0.60)
        "Vosk never broke a seal." They quotes a price before you have asked a question.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of vosk never broke a seal, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_secret
+ { has_asset("tally", 8) } [Pay for word of the patience is mortgaged. (8 tallies)]
    -> barter("s_hesper_mortgage", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("s_hesper_mortgage", 0.60)
        "The Patience is mortgaged." They quotes a price before you have asked a question.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of the patience is mortgaged, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_q4
+ { has_asset("tally", 8) } [Pay for word of it begins at the marl sluice-house. (8 tallies)]
    -> barter("c4b", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("c4b", 0.60)
        "It begins at the Marl sluice-house." They quotes a price before you have asked a question.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of it begins at the marl sluice-house, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_q5
+ { has_asset("tally", 8) } [Pay for word of expose the ledger. (8 tallies)]
    -> barter("c5b", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("c5b", 0.60)
        "Expose the ledger." They quotes a price before you have asked a question.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of expose the ledger, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub
