// ============================================================
// Toma Reedhand -- Eel-catcher. Gift: Eelskin Cloak.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "toma"
VAR location = "reedwick_marsh"
VAR npc_standing = "neutral"


=== toma ===
Toma Reedhand measures trust in eels, not tallies.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> toma_smalltalk
+ [Ask about what lives down there.] -> topic_beast
+ [Ask about who is paying whom.] -> topic_econ
+ [Ask about people.] -> topic_people
+ [Ask about where it is safe to walk.] -> topic_place
+ [Ask about harrow was silenced.] -> topic_q2
+ [Leave them to it.] -> END


= toma_smalltalk
They keeps working the net while he talks.  # NEEDS_HUMAN_WRITING
-> hub



= topic_beast
They measures trust in eels, not tallies, and this time it means something.  # NEEDS_HUMAN_WRITING
"Wights rise at slack." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_wight_slack", 1.0)
"Some wights remember." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_wight_pleads", 1.0)
"Gulchers shy from iron." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_gulcher_iron", 1.0)
"The kelpmother takes eels." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("b_kelp_tribute", 1.0)
-> hub


= topic_econ
They measures trust in eels, not tallies, and this time it means something.  # NEEDS_HUMAN_WRITING
"Eels cost six a bundle." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("e_eel_market", 1.0)
-> hub


= topic_people
They measures trust in eels, not tallies, and this time it means something.  # NEEDS_HUMAN_WRITING
"Wenna keeps a tide-bell." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_wenna", 1.0)
-> hub


= topic_place
They measures trust in eels, not tallies, and this time it means something.  # NEEDS_HUMAN_WRITING
"Follow the heron-stones." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_heron_stones", 1.0)
-> hub


= topic_q2
They measures trust in eels, not tallies, and this time it means something.  # NEEDS_HUMAN_WRITING
"Harrow was taken by the Stairs." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("c2c", 1.0)
-> hub
