// ============================================================
// Dame Perrin Vosk -- Retired customs inspector. Gift: Skeleton Seal.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "vosk"
VAR location = "customs_house"
VAR npc_standing = "neutral"


=== vosk ===
Dame Perrin Vosk still calls the customs house "my desk".  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> vosk_smalltalk
+ [Ask about where it is safe to walk.] -> topic_place
+ [Ask about route.] -> topic_route
+ [Ask about what people would rather keep.] -> topic_secret
+ [Ask about only the assize can free doon.] -> topic_q5
+ [Leave them to it.] -> END


= vosk_smalltalk
They folds her hands the way she once folded a warrant.  # NEEDS_HUMAN_WRITING
-> hub



= topic_place
They still calls the customs house "my desk", and this time it means something.  # NEEDS_HUMAN_WRITING
"The old ledgers are in the cellar." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("t_customs_cellar", 1.0)
-> hub


= topic_route
They still calls the customs house "my desk", and this time it means something.  # NEEDS_HUMAN_WRITING
"The gatehouse door knows a master seal." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("r_gate_seal", 1.0)
"Three witnesses convene the Assize." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("r_assize_call", 1.0)
-> hub


= topic_secret
They still calls the customs house "my desk", and this time it means something.  # NEEDS_HUMAN_WRITING
"Wimble sells the records." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("s_wimble_sells", 1.0)
-> hub


= topic_q5
They still calls the customs house "my desk", and this time it means something.  # NEEDS_HUMAN_WRITING
"Only the Assize can free Doon." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("c5a", 1.0)
-> hub
