// ============================================================
// Clerk Wimble -- Customs records clerk. Sells access.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "wimble"
VAR location = "customs_house"
VAR npc_standing = "neutral"


=== wimble ===
Clerk Wimble stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> wimble_smalltalk
+ [Ask about who is paying whom.] -> topic_econ
+ [Ask about people.] -> topic_people
+ [Ask about where it is safe to walk.] -> topic_place
+ [Ask about route.] -> topic_route
+ [Ask about what people would rather keep.] -> topic_secret
+ [Ask about harrow was silenced.] -> topic_q2
+ [Ask about it begins at the gatehouse.] -> topic_q4
+ [Ask about only the assize can free doon.] -> topic_q5
+ [Leave them to it.] -> END


= wimble_smalltalk
They glances at the door to Vosk's old office.  # NEEDS_HUMAN_WRITING
-> hub



= topic_econ
+ { has_asset("tally", 8) } [Pay for word of hearsay sells at half. (8 tallies)]
    -> barter("e_hearsay_half", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("e_hearsay_half", 0.60)
        "Hearsay sells at half." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of hearsay sells at half, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ { has_asset("tally", 8) } [Pay for word of the cellar costs eight. (8 tallies)]
    -> barter("e_customs_bribe", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("e_customs_bribe", 0.60)
        "The cellar costs eight." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of the cellar costs eight, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_people
+ { has_asset("tally", 8) } [Pay for word of ottoline pays double for the unique. (8 tallies)]
    -> barter("p_ottoline", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("p_ottoline", 0.60)
        "Ottoline pays double for the unique." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of ottoline pays double for the unique, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ { has_asset("tally", 8) } [Pay for word of vosk never broke a seal. (8 tallies)]
    -> barter("p_vosk", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("p_vosk", 0.60)
        "Vosk never broke a seal." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of vosk never broke a seal, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ { has_asset("tally", 8) } [Pay for word of corvin's pouch bears the tally seal. (8 tallies)]
    -> barter("p_corvin", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("p_corvin", 0.60)
        "Corvin's pouch bears the Tally seal." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of corvin's pouch bears the tally seal, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_place
+ { has_asset("tally", 8) } [Pay for word of the old ledgers are in the cellar. (8 tallies)]
    -> barter("t_customs_cellar", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("t_customs_cellar", 0.60)
        "The old ledgers are in the cellar." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of the old ledgers are in the cellar, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_route
+ { has_asset("tally", 8) } [Pay for word of the gatehouse door knows a master seal. (8 tallies)]
    -> barter("r_gate_seal", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("r_gate_seal", 0.60)
        "The gatehouse door knows a master seal." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of the gatehouse door knows a master seal, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_secret
+ { has_asset("tally", 8) } [Pay for word of the patience is mortgaged. (8 tallies)]
    -> barter("s_hesper_mortgage", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("s_hesper_mortgage", 0.60)
        "The Patience is mortgaged." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of the patience is mortgaged, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_q2
+ { has_asset("tally", 8) } [Pay for word of harrow was chased. (8 tallies)]
    -> barter("c2b", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("c2b", 0.60)
        "Harrow was chased." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of harrow was chased, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_q4
+ { has_asset("tally", 8) } [Pay for word of it begins at the marl sluice-house. (8 tallies)]
    -> barter("c4b", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("c4b", 0.60)
        "It begins at the Marl sluice-house." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of it begins at the marl sluice-house, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub


= topic_q5
+ { has_asset("tally", 8) } [Pay for word of expose the ledger. (8 tallies)]
    -> barter("c5b", 1, "tally", 8, npc_id, "") ->
    { barter_result == BARTER_BOUGHT:
        ~ learn("c5b", 0.60)
        "Expose the ledger." They stamps things that do not need stamping.  # NEEDS_HUMAN_WRITING
    }
    -> hub
+ [Ask the price of expose the ledger, empty-handed.]
    "8 tallies. Coin first."  # NEEDS_HUMAN_WRITING
    -> hub
+ [Not today.] -> hub
