// ============================================================
// Yarrow Thistle -- Tinker-widow. Gift: Truthglass.
// ============================================================
// *** GENERATED by tools/gen_dialogue.py from topics.json. Edit docs/slack_tide_spec.json
// and topics.json, not this file; re-run to regenerate.
// Every line below is a functional draft: # NEEDS_HUMAN_WRITING
// ============================================================

INCLUDE patterns.ink

VAR npc_id = "yarrow"
VAR location = "far_wend_landing"
VAR npc_standing = "neutral"


=== yarrow ===
Yarrow Thistle finishes your sentence wrong on purpose.  # NEEDS_HUMAN_WRITING
- (hub)
+ ["How are you keeping?"] -> yarrow_smalltalk
+ [Ask about people.] -> topic_people
+ [Ask about route.] -> topic_route
+ [Leave them to it.] -> END


= yarrow_smalltalk
They holds a thing up to the light before answering.  # NEEDS_HUMAN_WRITING
-> hub



= topic_people
They finishes your sentence wrong on purpose, and this time it means something.  # NEEDS_HUMAN_WRITING
"Croy keeps a wick-staff." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_croy", 1.0)
"Brack's blade drank the Lull." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("p_brack", 1.0)
-> hub


= topic_route
They finishes your sentence wrong on purpose, and this time it means something.  # NEEDS_HUMAN_WRITING
"Turning Word: second." They say it once and do not repeat it.  # NEEDS_HUMAN_WRITING
~ learn("r_word_2", 1.0)
-> hub
